### ISSUE TITLE
Some files skipped when exporting

### ISSUE THREAD

**Issue by hadingtid** [hagent/export-macos-podcasts#1]
Thanks for going to the effort to write this script. When I try to export my podcast library (~100 GB) it manages to export the majority (~85 GB), but exits with an error.

`[Error: ENOENT: no such file or directory, copyfile '/Users/user/Library/Group Containers/243LU875E5.groups.com.apple.podcasts/Library/Cache/018EA0D0-6F6A-44EA-9112-D46EBE506967.mp3' -> '/Users/user/Downloads/PodcastsExport/2021.12.25/travail contre la liberté (4/4) : Quand les esclav.mp3'] {
  errno: -2,
  code: 'ENOENT',
  syscall: 'copyfile',
  path: '/Users/user/Library/Group Containers/243LU875E5.groups.com.apple.podcasts/Library/Cache/018EA0D0-6F6A-44EA-9112-D46EBE506967.mp3',
  dest: '/Users/user/Downloads/PodcastsExport/2021.12.25/travail contre la liberté (4/4) : Quand les esclav.mp3'
}`

Here it seems likely that the character `:` is responsible, and I think in some other files have `/` in their name too. Is there a method to replace these with underscores or hyphens?

**Comment by hagent** [comment]
@hadingtid hi, should work now :)
